PiecesCandyCo/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PiecesCandyCo.DataAccess;
using PiecesCandyCo.DataAccess.Data;
using PiecesCandyCo.DataAccess.Repository.IRepository;
using PiecesCandyCo.Models;
using PiecesCandyCo.Utility;

namespace PiecesCandyCo.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]
    public class CategoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CategoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public IActionResult Index()
        {
            List<Category> categoryList = _unitOfWork.Category.GetAll().ToList();
            return View(categoryList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category category)
        {
            if (category.Name == category.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "The Category Name cannot match the Display Order.");
            }
            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Add(category);
                _unitOfWork.Save();
                TempData["success"] = "Category created successfully.";
                return RedirectToAction("Index");
            }
            return View(category);


        }

        public IActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category categorySelected = _unitOfWork.Category.Get(u => u.Id == id);
            if (categorySelected == null)
            {
                return NotFound();
            }
            return View(categorySelected);
        }

        [HttpPost]
        public IActionResult Edit(Category category)
        {

            if (ModelState.IsValid)
            {
                _unitOfWork.Category.Update(category);
                _unitOfWork.Save();
                TempData["success"] = "Category updated successfully.";
                return RedirectToAction("Index");
            }

            return View(category);


        }

        public IActionResult Delete(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category categorySelected = _unitOfWork.Category.Get(u => u.Id == id);
            if (categorySelected == null)
            {
                return NotFound();
            }
            return View(categorySelected);
        }

        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int id)
        {
            Category categorySelected = _unitOfWork.Category.Get(u => u.Id == id);
            if (categorySelected == null)
            {
                return NotFound();
            }
            _unitOfWork.Category.Remove(categorySelected);
            _unitOfWork.Save();
            TempData["success"] = "Category deleted successfully.";
            return RedirectToAction("Index");


        }



    }
}

PiecesCandyCo/Areas/Admin/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using PiecesCandyCo.DataAccess.Repository.IRepository;
using PiecesCandyCo.Models;
using PiecesCandyCo.Models.ViewModels;
using PiecesCandyCo.Utility;
using Stripe;
using System.Security.Claims;

namespace PiecesCandyCo.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class OrderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }

        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId)
        {
            OrderVM = new()
            {
                CustomerOrderDetail = _unitOfWork.CustomerOrderDetail.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                CartOrderDetail = _unitOfWork.CartOrderDetail.GetAll(u => u.CustomerOrderDetailId == orderId, includeProperties: "Product")
            };
            return View(OrderVM);
        }


        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult UpdateOrderDetail()
        {
            var customerOrderDetailFromDb = _unitOfWork.CustomerOrderDetail.Get(u => u.Id == OrderVM.CustomerOrderDetail.Id);
            customerOrderDetailFromDb.Name = OrderVM.CustomerOrderDetail.Name;
            customerOrderDetailFromDb.PhoneNumber = OrderVM.CustomerOrderDetail.PhoneNumber;
            customerOrderDetailFromDb.StreetAddress = OrderVM.CustomerOrderDetail.StreetAddress;
            customerOrderDetailFromDb.City = OrderVM.CustomerOrderDetail.City;
            customerOrderDetailFromDb.State = OrderVM.CustomerOrderDetail.State;
            customerOrderDetailFromDb.ZipCode = OrderVM.CustomerOrderDetail.ZipCode;

            if (!string.IsNullOrEmpty(OrderVM.CustomerOrderDetail.Carrier))
            {
                customerOrderDetailFromDb.Carrier = OrderVM.CustomerOrderDetail.Carrier;
            }
            if (!string.IsNullOrEmpty(OrderVM.CustomerOrderDetail.TrackingNumber))
            {
                customerOrderDetailFromDb.TrackingNumber = OrderVM.CustomerOrderDetail.TrackingNumber;
            }
            _unitOfWork.CustomerOrderDetail.Update(customerOrderDetailFromDb);
            _unitOfWork.Save();

            TempData["Success"] = "Order Details Updated Succesfully!";

            return RedirectToAction(nameof(Details), new { orderId = customerOrderDetailFromDb.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult ShipOrder()
        {
            var customerOrderDetail = _unitOfWork.CustomerOrderDetail.Get(u => u.Id == OrderVM.CustomerOrderDetail.Id);
            customerOrderDetail.TrackingNumber = OrderVM.CustomerOrderDetail.TrackingNumber;
            customerOrderDetail.Carrier = OrderVM.CustomerOrderDetail.Carrier;
            customerOrderDetail.OrderStatus = SD.StatusShipped;
            customerOrderDetail.ShipDate = DateTime.Now;

            _unitOfWork.CustomerOrderDetail.Update(customerOrderDetail);
            _unitOfWork.Save(); 
            TempData["Success"] = "Order Shipped Succesfully!";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.CustomerOrderDetail.Id });
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_Admin)]
        public IActionResult CancelOrder()
        {
            var customerOrderDetail = _unitOfWork.CustomerOrderDetail.Get(u => u.Id == OrderVM.CustomerOrderDetail.Id);
            if (customerOrderDetail.PaymentStatus == SD.PaymentStatusApproved)
            {
                var refundOption = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = customerOrderDetail.PaymentIntentId
                };

                var refundService = new RefundService();
                Refund refund = refundService.Create(refundOption);

                _unitOfWork.CustomerOrderDetail.UpdateStatus(customerOrderDetail.Id, SD.StatusCancelled, SD.PaymentStatusRefunded);
            }
            else
            {
                _unitOfWork.CustomerOrderDetail.UpdateStatus(customerOrderDetail.Id, SD.StatusCancelled, SD.StatusCancelled);
            }

            _unitOfWork.Save();
            TempData["Success"] = "Order Cancelled Succesfully!";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.CustomerOrderDetail.Id });
        }


            #region API CALLS

        [HttpGet]
        [Authorize]
        public IActionResult GetAll()
        {
            IEnumerable<CustomerOrderDetail> customerOrderDetails1;

            if (User.IsInRole(SD.Role_Admin))
            {
                customerOrderDetails1 = _unitOfWork.CustomerOrderDetail.GetAll(includeProperties: "ApplicationUser").ToList();

            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                customerOrderDetails1 = _unitOfWork.CustomerOrderDetail.GetAll(u => u.ApplicationUserId == userId, includeProperties: "ApplicationUser");
            }
            return Json (new {data = customerOrderDetails1});
        }

        #endregion
    }
}

PiecesCandyCo/ViewComponents/ShoppingCartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PiecesCandyCo.DataAccess.Repository.IRepository;
using PiecesCandyCo.Utility;
using System.Security.Claims;

namespace PiecesCandyCo.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;
        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart, _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == claim.Value).Count());
                    
                }

                
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);
            }
        }
    }
}

PiecesCandyCo/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="/favicon-32x32_1.png" type="image/x-icon">
    <title>@ViewData["Title"] Pieces Candy Co.</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/PiecesCandyCo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3 mt-20">
            <div class="container-fluid">

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index"><i class="bi bi-house-heart"></i></a>
                        </li>
                        @if (User.IsInRole(SD.Role_Admin) || User.IsInRole(SD.Role_Customer))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="Admin" asp-controller="Order" asp-action="Index"><i class="bi bi-truck"></i> Orders</a>
                            </li>
                        }
                        @if (User.IsInRole(SD.Role_Admin))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-gear-fill text-light"></i> Admin
                                </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Manage Categories</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Manage Products</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>


                                </ul>
                            </li>
                        }


                    </ul>
                    
                    <partial name="_LoginPartial" />

                    <div class="px-2">
                        <a class="nav-link text-light" asp-area="Customer" asp-controller="ShoppingCart" asp-action="Index">
                            @await Component.InvokeAsync("ShoppingCart")
                        </a>
                    </div>


                </div>
            </div>
        </nav>
        <div class="container">
            <div class="row">
                <div class="col text-center mb-2">
                    <a asp-area="Customer" asp-controller="Home" asp-action="Index">
                    <img src="/images/logos/Pieceshomemain2.png" class="img-fluid mx-auto d-block"  alt="Centered Logo">
                    </a>

                </div>
            </div>
        </div>



        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - <i class="bi bi-bag-heart-fill"></i> Pieces Candy Co.

        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="//cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PiecesCandyCo/Views/Shared/_NotificationPartial.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}